### PR TITLE
Added useful doc

### PR DESCRIPTION
**Pull request by PurHur**
Please merge # **ASAP**

### CODE REVIEW

**Comment by PurHur** [comment]
#3 rELATED iSSUE

pLS RESPOND ASAP!!!

**Comment by peterwankman** [comment]
Not mission critical

**Comment by PurHur** [comment]
;_; so much people need this information
please merge ASAP

**Comment by peterwankman** [comment]
Please correct spelling mistakes. Please state the encoding of the fields of the database. Please state the size and signedness of the integers. Please convert specification to texinfo. Please stop harassing me.

**Comment by PurHur** [comment]
Make ffd great again.

**Comment by peterwankman** [comment]
Merge does not meet quality standards.
PurHur does not meet odour standards.

**Pull request closed without merging**
